import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "@/components/Navbar";
import { Inter } from 'next/font/google';
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({style:'normal',subsets:['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ inter.className}
      >
        <NavigationBar></NavigationBar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
