import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "@/components/Navbar";
import { Merriweather } from 'next/font/google';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const merriweather = Merriweather({style:'normal',weight:"300",subsets:['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ merriweather.className}
      >
        <NavigationBar></NavigationBar>
        {children}
      </body>
    </html>
  );
}
